version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing SAM CLI..."
      - pip install aws-sam-cli
  build:
    commands:
      - echo "Building the project..."
      - mvn clean install
      - echo "Packaging with SAM..."
      - sam package --template-file templateSAM.yml --s3-bucket gor-barseghyan-site --output-template-file packaged.yml

artifacts:
  type: zip
  files:
    - packaged.yml
