version: 0.2

phases:
  pre_build:
    commands:
      - echo "ðŸ” Logging in to ECR"
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 151182332702.dkr.ecr.us-east-2.amazonaws.com
      - export REPO_URI=151182332702.dkr.ecr.us-east-2.amazonaws.com/gorb/aws-task
      - export IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-7)

  build:
    commands:
      # â”€â”€ 1ï¸âƒ£  build the web-app JAR â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
      - echo "ðŸ›   Building Spring-Boot web app"
      - mvn -q -f awstask/pom.xml -DskipTests package

      # â”€â”€ 2ï¸âƒ£  build + tag Docker image â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
      - echo "ðŸ³  Building Docker image"
      - docker build -t $REPO_URI:$IMAGE_TAG -f awstask/Dockerfile awstask
      - docker tag  $REPO_URI:$IMAGE_TAG  $REPO_URI:latest

      # â”€â”€ 3ï¸âƒ£  build the Lambda JAR â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
      - echo "ðŸ›   Building Lambda shaded JAR"
      - mvn -q -f lambda/pom.xml -Pshade -DskipTests package

      # â”€â”€ 4ï¸âƒ£  package SAM template â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
      - sam package --template-file templateSAM.yml --s3-bucket gor-barseghyan-site --output-template-file packaged.yml

  post_build:
    commands:
      - echo "ðŸ“¤ Pushing Docker image"
      - docker push $REPO_URI:$IMAGE_TAG
      - docker push $REPO_URI:latest
      - echo "ðŸ“ Writing imagedefinitions.json"
      - printf '[{"name":"GorB-image-app","imageUri":"%s"}]' $REPO_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - packaged.yml              # for Lambda stack
    - ecs-stack.yml             # if stored in repo (you can also inline)
    - imagedefinitions.json     # optional (only if using CodeDeploy to ECS)
