version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing SAM CLI …"
      - pip install --quiet aws-sam-cli
  build:
    commands:
      - echo "Building JAR …"
      - mvn -B clean package             # creates target/lambda-0.0.1-SNAPSHOT.jar
      - echo "Packaging with SAM …"
      - sam package --template-file templateSAM.yml \
                    --s3-bucket gor-barseghyan-site \
                    --output-template-file packaged.yml
artifacts:
  files:
    - packaged.yml                       # <- CodePipeline deploy stage needs this
  discard-paths: yes
